name: Validate

on: 
  - push
  - pull_request

jobs:

  yaml_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install yamllint
      run: sudo apt-get install -y yamllint
    - name: Lint
      run: yamllint -d relaxed plugins.yaml
