name: Validate

on: 
  push:
  schedule:
    - cron: "0 */6 * * *"

jobs:

  yaml_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: manifests/
  
  check_urls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install -r scripts/requirements.txt
      - name: Check URLs
        run: python3 scripts/check_urls.py manifests/
